[package]
name = "apk-wasm-bindings"
version = "0.1.0"
edition = "2021"

[package.metadata.wasm-pack.profile.release]
# Workaround for https://github.com/rustwasm/wasm-pack/issues/1441
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
abxml-wasm-common = { path = "../abxml-wasm-common" }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
tsify = "0.5.6"
serde = { version = "1.0", features = ["derive"] }
getrandom = { version = "0.2.15", features = ["js"] }
