// @ts-ignore: erofs.js is generated by emcc
import createErofsModule from './erofs.js';

let erofsModulePromise: Promise<any> | null = null;

export async function getErofsModule() {
    if (!erofsModulePromise) {
        erofsModulePromise = createErofsModule({
            locateFile: (path: string) => {
                if (path.endsWith('.wasm')) {
                    return new URL('erofs.wasm', import.meta.url).href;
                }
                return path;
            }
        });
    }
    return erofsModulePromise;
}

export async function parseErofs(data: Uint8Array): Promise<any> {
    const mod = await getErofsModule();
    const filename = `/img_${Date.now()}_${Math.random().toString(36).substring(2)}.erofs`;
    mod.FS.writeFile(filename, data);
    try {
        const ptr = mod.ccall('api_parse_erofs', 'number', ['string'], [filename]);
        if (!ptr) {
            throw new Error("Failed to parse EROFS filesystem.");
        }
        const jsonStr = mod.UTF8ToString(ptr);
        mod.ccall('api_free_buf', 'void', ['number'], [ptr]);
        return JSON.parse(jsonStr);
    } finally {
        try {
            mod.FS.unlink(filename);
        } catch (e) {
            // ignore cleanup error
        }
    }
}

export async function readErofsFile(data: Uint8Array, filePath: string): Promise<Uint8Array> {
    const mod = await getErofsModule();
    const filename = `/img_${Date.now()}_${Math.random().toString(36).substring(2)}.erofs`;
    mod.FS.writeFile(filename, data);
    try {
        const sizePtr = mod._malloc(4);
        const filePtr = mod.ccall('api_read_file', 'number', ['string', 'string', 'number'], [filename, filePath, sizePtr]);
        if (!filePtr) {
            mod._free(sizePtr);
            throw new Error(`Failed to read file ${filePath} from EROFS.`);
        }
        const size = mod.HEAPU32[sizePtr / 4];
        const content = new Uint8Array(mod.HEAPU8.subarray(filePtr, filePtr + size));
        mod.ccall('api_free_buf', 'void', ['number'], [filePtr]);
        mod._free(sizePtr);
        return content;
    } finally {
        try {
            mod.FS.unlink(filename);
        } catch (e) {
            // ignore cleanup error
        }
    }
}
