/**
 * worker.ts: Web Worker for SELinux Policy Analysis
 *
 * This worker manages the lifecycle of the libsepol-based WASM module and
 * provides an asynchronous interface for parsing and searching binary policies.
 */

// @ts-ignore: sepolicy.js is generated by emcc
import createSepolicyModule from './sepolicy.js';

let mod: any = null;
let policyPtr: number = 0;
let ruleCount: number = 0;

/**
 * Symbol types as defined in libsepol/include/sepol/policydb/policydb.h
 */
const SYM_COMMONS = 0;
const SYM_CLASSES = 1;
const SYM_ROLES = 2;
const SYM_TYPES = 3;
const SYM_USERS = 4;
const SYM_BOOLS = 5;

/**
 * Access Vector Table specified bits as defined in libsepol/include/sepol/policydb/avtab.h
 */
const AVTAB_ALLOWED = 0x0001;
const AVTAB_AUDITALLOW = 0x0002;
const AVTAB_AUDITDENY = 0x0004; // Used for dontaudit
const AVTAB_NEVERALLOW = 0x0080;

self.onmessage = async (e: MessageEvent) => {
    const { action, buffer, query, isRegex, ruleType, typeName, transitive } = e.data;

    if (action === 'parse') {
        try {
            if (!mod) {
                mod = await createSepolicyModule({
                    locateFile: (path: string) => {
                        if (path.endsWith('.wasm')) {
                            return new URL('sepolicy.wasm', import.meta.url).href;
                        }
                        return path;
                    }
                });
            }

            if (policyPtr) {
                mod.ccall('api_free_policy', 'void', ['number'], [policyPtr]);
                policyPtr = 0;
            }

            const uint8Buffer = new Uint8Array(buffer);
            const dataPtr = mod._malloc(uint8Buffer.length);
            mod.HEAPU8.set(uint8Buffer, dataPtr);

            // Detect if it's a CIL file (simple check for '(' as first non-whitespace)
            let isCil = false;
            for (let i = 0; i < uint8Buffer.length; i++) {
                if (uint8Buffer[i] > 32) {
                    if (uint8Buffer[i] === 40) isCil = true; // '('
                    break;
                }
            }

            if (isCil) {
                policyPtr = mod.ccall('api_load_cil', 'number', ['number', 'number'], [dataPtr, uint8Buffer.length]);
            } else {
                policyPtr = mod.ccall('api_load_policy', 'number', ['number', 'number'], [dataPtr, uint8Buffer.length]);
            }

            mod._free(dataPtr);

            if (!policyPtr) {
                throw new Error("Failed to load policy. Ensure it is a valid SELinux binary or CIL policy.");
            }

            // Extract metadata
            const version = mod.ccall('api_get_version', 'number', ['number'], [policyPtr]);

            const counts = {
                classes: mod.ccall('api_get_symbol_count', 'number', ['number', 'number'], [policyPtr, SYM_CLASSES]),
                roles: mod.ccall('api_get_symbol_count', 'number', ['number', 'number'], [policyPtr, SYM_ROLES]),
                types: mod.ccall('api_get_symbol_count', 'number', ['number', 'number'], [policyPtr, SYM_TYPES]),
                users: mod.ccall('api_get_symbol_count', 'number', ['number', 'number'], [policyPtr, SYM_USERS]),
                bools: mod.ccall('api_get_symbol_count', 'number', ['number', 'number'], [policyPtr, SYM_BOOLS]),
                rules: mod.ccall('api_get_rule_count', 'number', ['number', 'number'], [policyPtr, AVTAB_ALLOWED]),
                auditallow: mod.ccall('api_get_rule_count', 'number', ['number', 'number'], [policyPtr, AVTAB_AUDITALLOW]),
                dontaudit: mod.ccall('api_get_rule_count', 'number', ['number', 'number'], [policyPtr, AVTAB_AUDITDENY]),
                neverallow: mod.ccall('api_get_rule_count', 'number', ['number', 'number'], [policyPtr, AVTAB_NEVERALLOW]),
            };
            ruleCount = counts.rules;

            // Extract symbols (limited for types to avoid UI lag on massive policies)
            const symbols: any = {
                types: [],
                attributes: [],
                roles: [],
                classes: [],
                users: [],
                bools: []
            };

            for (let i = 1; i <= counts.types; i++) {
                const name = mod.ccall('api_get_symbol_name', 'string', ['number', 'number', 'number'], [policyPtr, SYM_TYPES, i]);
                if (name) {
                    const isAttr = mod.ccall('api_is_type_attribute', 'number', ['number', 'number'], [policyPtr, i]);
                    if (isAttr === 1) symbols.attributes.push(name);
                    else symbols.types.push(name);
                }
            }

            const extractNames = (symType: number, count: number, target: string[]) => {
                for (let i = 1; i <= count; i++) {
                    const name = mod.ccall('api_get_symbol_name', 'string', ['number', 'number', 'number'], [policyPtr, symType, i]);
                    if (name) target.push(name);
                }
            };

            extractNames(SYM_ROLES, counts.roles, symbols.roles);
            extractNames(SYM_CLASSES, counts.classes, symbols.classes);
            extractNames(SYM_USERS, counts.users, symbols.users);

            for (let i = 1; i <= counts.bools; i++) {
                const name = mod.ccall('api_get_symbol_name', 'string', ['number', 'number', 'number'], [policyPtr, SYM_BOOLS, i]);
                if (name) {
                    const state = mod.ccall('api_get_boolean_state', 'number', ['number', 'number'], [policyPtr, i]);
                    symbols.bools.push(`${name} (${state === 1 ? 'true' : 'false'})`);
                }
            }

            self.postMessage({
                action: 'parsed',
                version,
                counts,
                symbols
            });

        } catch (error: any) {
            console.error(error);
            self.postMessage({ error: error.message });
        }
    } else if (action === 'search') {
        // Perform search across rules in the Access Vector Table based on ruleType.
        // The search logic is moved to the C bridge for performance on large policies.
        if (!policyPtr || !mod) return;

        let mask = AVTAB_ALLOWED;
        let prefix = "allow";
        let countLimit = ruleCount;

        if (ruleType === 'auditallow') {
            mask = AVTAB_AUDITALLOW;
            prefix = "auditallow";
            countLimit = mod.ccall('api_get_rule_count', 'number', ['number', 'number'], [policyPtr, AVTAB_AUDITALLOW]);
        } else if (ruleType === 'dontaudit') {
            mask = AVTAB_AUDITDENY;
            prefix = "dontaudit";
            countLimit = mod.ccall('api_get_rule_count', 'number', ['number', 'number'], [policyPtr, AVTAB_AUDITDENY]);
        } else if (ruleType === 'neverallow') {
            mask = AVTAB_NEVERALLOW;
            prefix = "neverallow";
            countLimit = mod.ccall('api_get_rule_count', 'number', ['number', 'number'], [policyPtr, AVTAB_NEVERALLOW]);
        }

        // Use the rule count for the specific type as the limit for rule collection.
        const maxCollect = countLimit || 1000;
        const structSize = 16;   // 4 * uint32 (src_id, tgt_id, class_id, av_bits)
        const resultsPtr = mod._malloc(maxCollect * structSize);
        if (!resultsPtr) {
            console.error("Failed to allocate memory for rules");
            self.postMessage({ action: 'results', results: [], ruleType });
            return;
        }

        // Query the C bridge which maps the avtab and filters by symbol names and mask.
        // Pass isRegex flag to enable POSIX regex matching in the C logic.
        const actualCount = mod.ccall('api_get_rules', 'number', ['number', 'number', 'number', 'string', 'number', 'number'],
                                    [policyPtr, resultsPtr, maxCollect, query || "", isRegex ? 1 : 0, mask]);

        const rules = [];

        // Read results from the WASM heap.
        const heap32 = mod.HEAPU32 || new Uint32Array(mod.wasmMemory.buffer);

        for (let i = 0; i < actualCount; i++) {
            const base = (resultsPtr / 4) + (i * 4);
            const src = heap32[base];
            const tgt = heap32[base + 1];
            const clsWithMask = heap32[base + 2];
            const data = heap32[base + 3];

            const cls = clsWithMask & 0xFFFF;

            // Resolve 1-based IDs back to human-readable names.
            const srcName = mod.ccall('api_get_symbol_name', 'string', ['number', 'number', 'number'], [policyPtr, SYM_TYPES, src]);
            const tgtName = mod.ccall('api_get_symbol_name', 'string', ['number', 'number', 'number'], [policyPtr, SYM_TYPES, tgt]);
            const clsName = mod.ccall('api_get_symbol_name', 'string', ['number', 'number', 'number'], [policyPtr, SYM_CLASSES, cls]);

            // Resolve access vector bits to human-readable permissions using libsepol's utility.
            const permsPtr = mod.ccall('api_get_permissions', 'number', ['number', 'number', 'number'], [policyPtr, cls, data]);
            let perms = permsPtr ? mod.UTF8ToString(permsPtr).trim() : `0x${data.toString(16)}`;

            // sepol_av_to_string returns a space-separated list of permissions.
            // If multiple permissions are present, it does NOT wrap them in braces,
            // but we want our output to always have braces for consistency.
            rules.push(`${prefix} ${srcName} ${tgtName}:${clsName} { ${perms} };`);

            // Free the string allocated by the C library (sepol_av_to_string uses realloc/malloc).
            if (permsPtr) {
                mod.ccall('api_free_string', 'void', ['number'], [permsPtr]);
            }
        }

        mod._free(resultsPtr);
        self.postMessage({ action: 'results', results: rules, ruleType });
    } else if (action === 'get_type_details') {
        if (!policyPtr || !mod || !typeName) return;

        // Find type ID by name
        const counts = {
            types: mod.ccall('api_get_symbol_count', 'number', ['number', 'number'], [policyPtr, SYM_TYPES]),
        };

        let typeId = -1;
        for (let i = 1; i <= counts.types; i++) {
            const name = mod.ccall('api_get_symbol_name', 'string', ['number', 'number', 'number'], [policyPtr, SYM_TYPES, i]);
            if (name === typeName) {
                typeId = i;
                break;
            }
        }

        if (typeId === -1) {
            self.postMessage({ action: 'type_details', error: 'Type not found' });
            return;
        }

        // Get attributes
        const maxAttrs = 256;
        const attrsPtr = mod._malloc(maxAttrs * 4);
        const attrCount = mod.ccall('api_get_type_attributes', 'number', ['number', 'number', 'number', 'number'], [policyPtr, typeId, attrsPtr, maxAttrs]);

        const attributes = [];
        const heap32 = mod.HEAPU32 || new Uint32Array(mod.wasmMemory.buffer);
        for (let i = 0; i < attrCount; i++) {
            const attrId = heap32[(attrsPtr / 4) + i];
            const name = mod.ccall('api_get_symbol_name', 'string', ['number', 'number', 'number'], [policyPtr, SYM_TYPES, attrId]);
            if (name) attributes.push(name);
        }
        mod._free(attrsPtr);

        // Get rules
        const masks = [AVTAB_ALLOWED, AVTAB_AUDITALLOW, AVTAB_AUDITDENY, AVTAB_NEVERALLOW];
        const prefixes = ["allow", "auditallow", "dontaudit", "neverallow"];
        const allRules: string[] = [];

        const maxRules = 2000;
        const rulesPtr = mod._malloc(maxRules * 16);

        for (let m = 0; m < masks.length; m++) {
            const actualCount = mod.ccall('api_get_rules_for_type', 'number', ['number', 'number', 'number', 'number', 'number', 'number'],
                                        [policyPtr, rulesPtr, maxRules, typeId, transitive ? 1 : 0, masks[m]]);

            for (let i = 0; i < actualCount; i++) {
                const base = (rulesPtr / 4) + (i * 4);
                const src = heap32[base];
                const tgt = heap32[base + 1];
                const clsWithMask = heap32[base + 2];
                const data = heap32[base + 3];

                const cls = clsWithMask & 0xFFFF;

                const srcName = mod.ccall('api_get_symbol_name', 'string', ['number', 'number', 'number'], [policyPtr, SYM_TYPES, src]);
                const tgtName = mod.ccall('api_get_symbol_name', 'string', ['number', 'number', 'number'], [policyPtr, SYM_TYPES, tgt]);
                const clsName = mod.ccall('api_get_symbol_name', 'string', ['number', 'number', 'number'], [policyPtr, SYM_CLASSES, cls]);
                const permsPtr = mod.ccall('api_get_permissions', 'number', ['number', 'number', 'number'], [policyPtr, cls, data]);
                let perms = permsPtr ? mod.UTF8ToString(permsPtr).trim() : `0x${data.toString(16)}`;

                allRules.push(`${prefixes[m]} ${srcName} ${tgtName}:${clsName} { ${perms} };`);

                if (permsPtr) mod.ccall('api_free_string', 'void', ['number'], [permsPtr]);
            }
        }

        mod._free(rulesPtr);
        self.postMessage({ action: 'type_details', typeName, attributes, rules: allRules });
    }
}
