/**
 * worker.ts: Web Worker for SELinux Policy Analysis
 *
 * This worker manages the lifecycle of the libsepol-based WASM module and
 * provides an asynchronous interface for parsing and searching binary policies.
 */

// @ts-ignore: sepolicy.js is generated by emcc
import createSepolicyModule from './sepolicy.js';

let mod: any = null;
let policyPtr: number = 0;

/**
 * Symbol types as defined in libsepol/include/sepol/policydb/policydb.h
 */
const SYM_COMMONS = 0;
const SYM_CLASSES = 1;
const SYM_ROLES = 2;
const SYM_TYPES = 3;
const SYM_USERS = 4;
const SYM_BOOLS = 5;

self.onmessage = async (e: MessageEvent) => {
    const { action, buffer, query } = e.data;

    if (action === 'parse') {
        try {
            // Initialize WASM module if not already done
            if (!mod) {
                mod = await createSepolicyModule({
                    locateFile: (path: string) => {
                        if (path.endsWith('.wasm')) {
                            // Ensure we load the WASM file from the correct relative path
                            return new URL('sepolicy.wasm', import.meta.url).href;
                        }
                        return path;
                    }
                });
            }

            // Free previous policy if one was loaded
            if (policyPtr) {
                mod.ccall('api_free_policy', 'void', ['number'], [policyPtr]);
                policyPtr = 0;
            }

            // Load the new policy buffer into WASM memory
            const uint8Buffer = new Uint8Array(buffer);

            // Using explicit allocation instead of 'array' type in ccall to handle large buffers more reliably
            const dataPtr = mod._malloc(uint8Buffer.length);
            mod.HEAPU8.set(uint8Buffer, dataPtr);

            policyPtr = mod.ccall('api_load_policy', 'number', ['number', 'number'], [dataPtr, uint8Buffer.length]);

            // The memory for the buffer can be freed after api_load_policy since it copies or processes the data
            mod._free(dataPtr);

            if (!policyPtr) {
                throw new Error("Failed to load policy. Ensure it is a valid SELinux binary policy.");
            }

            // Extract metadata
            const version = mod.ccall('api_get_version', 'number', ['number'], [policyPtr]);

            const counts = {
                classes: mod.ccall('api_get_symbol_count', 'number', ['number', 'number'], [policyPtr, SYM_CLASSES]),
                roles: mod.ccall('api_get_symbol_count', 'number', ['number', 'number'], [policyPtr, SYM_ROLES]),
                types: mod.ccall('api_get_symbol_count', 'number', ['number', 'number'], [policyPtr, SYM_TYPES]),
                users: mod.ccall('api_get_symbol_count', 'number', ['number', 'number'], [policyPtr, SYM_USERS]),
                bools: mod.ccall('api_get_symbol_count', 'number', ['number', 'number'], [policyPtr, SYM_BOOLS]),
                rules: mod.ccall('api_get_rule_count', 'number', ['number'], [policyPtr])
            };

            // Extract symbols (limited for types to avoid UI lag on massive policies)
            const symbols: any = {
                types: [],
                attributes: [],
                roles: [],
                classes: [],
                users: [],
                bools: []
            };

            for (let i = 1; i <= counts.types; i++) {
                const name = mod.ccall('api_get_symbol_name', 'string', ['number', 'number', 'number'], [policyPtr, SYM_TYPES, i]);
                if (name) {
                    const isAttr = mod.ccall('api_is_type_attribute', 'number', ['number', 'number'], [policyPtr, i]);
                    if (isAttr === 1) symbols.attributes.push(name);
                    else symbols.types.push(name);
                }
                if (i > 10000) break; // Safety limit for symbol extraction
            }

            const extractNames = (symType: number, count: number, target: string[]) => {
                for (let i = 1; i <= count; i++) {
                    const name = mod.ccall('api_get_symbol_name', 'string', ['number', 'number', 'number'], [policyPtr, symType, i]);
                    if (name) target.push(name);
                }
            };

            extractNames(SYM_ROLES, counts.roles, symbols.roles);
            extractNames(SYM_CLASSES, counts.classes, symbols.classes);
            extractNames(SYM_USERS, counts.users, symbols.users);

            for (let i = 1; i <= counts.bools; i++) {
                const name = mod.ccall('api_get_symbol_name', 'string', ['number', 'number', 'number'], [policyPtr, SYM_BOOLS, i]);
                if (name) {
                    const state = mod.ccall('api_get_boolean_state', 'number', ['number', 'number'], [policyPtr, i]);
                    symbols.bools.push(`${name} (${state === 1 ? 'true' : 'false'})`);
                }
            }

            self.postMessage({
                action: 'parsed',
                version,
                counts,
                symbols
            });

        } catch (error: any) {
            console.error(error);
            self.postMessage({ error: error.message });
        }
    } else if (action === 'search') {
        // Perform search across all allow rules in the Access Vector Table.
        // The search logic is moved to the C bridge for performance on large policies.
        if (!policyPtr || !mod) return;

        const maxCollect = 20000; // Result set cap for the UI
        const structSize = 16;   // 4 * uint32 (src_id, tgt_id, class_id, av_bits)
        const resultsPtr = mod._malloc(maxCollect * structSize);
        if (!resultsPtr) {
            console.error("Failed to allocate memory for rules");
            self.postMessage({ action: 'results', results: [] });
            return;
        }

        // Query the C bridge which maps the avtab and filters by symbol names.
        const actualCount = mod.ccall('api_get_rules', 'number', ['number', 'number', 'number', 'string'],
                                    [policyPtr, resultsPtr, maxCollect, query || ""]);

        const rules = [];

        // Read results from the WASM heap.
        const heap32 = mod.HEAPU32 || new Uint32Array(mod.wasmMemory.buffer);

        for (let i = 0; i < actualCount; i++) {
            const base = (resultsPtr / 4) + (i * 4);
            const src = heap32[base];
            const tgt = heap32[base + 1];
            const cls = heap32[base + 2];
            const data = heap32[base + 3];

            // Resolve 1-based IDs back to human-readable names.
            const srcName = mod.ccall('api_get_symbol_name', 'string', ['number', 'number', 'number'], [policyPtr, SYM_TYPES, src]);
            const tgtName = mod.ccall('api_get_symbol_name', 'string', ['number', 'number', 'number'], [policyPtr, SYM_TYPES, tgt]);
            const clsName = mod.ccall('api_get_symbol_name', 'string', ['number', 'number', 'number'], [policyPtr, SYM_CLASSES, cls]);

            rules.push(`allow ${srcName} ${tgtName}:${clsName} { 0x${data.toString(16)} };`);
        }

        mod._free(resultsPtr);
        self.postMessage({ action: 'results', results: rules });
    }
}
