name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive

      - name: Set up Emscripten
        if: github.event.action != 'closed'
        uses: mymindstorm/setup-emsdk@6ab9eb1bda2574c4ddb79809fc9247783eaf9021 # v14
        with:
          version: "4.0.22"
          actions-cache-folder: "emsdk-cache"

      - name: Set up Go
        if: github.event.action != 'closed'
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: "1.23.4"
          cache-dependency-path: |
            protoscope/go.sum
            dexviewer/godexviewer/go.sum
            der/wasm/go.sum

      - name: Rust Target
        if: github.event.action != 'closed'
        run: |
          rustup target add wasm32-unknown-unknown

      - name: Rust Cache
        if: github.event.action != 'closed'
        uses: swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2

      - name: Use Node.js
        if: github.event.action != 'closed'
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Cache Turbo
        if: github.event.action != 'closed'
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        if: github.event.action != 'closed'
        run: npm ci

      - name: Build
        if: github.event.action != 'closed'
        run: npm run build

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist/
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
